export type AlertSeverity = 1 | 2 | 3 | 4 | 5;

export type AlertRuleDefinition = {
  ruleId: string;
  severity: AlertSeverity;
  title: string;
  description: string;
  fingerprintStrategy: string;
  evidenceFields: string[];
  resolutionCondition: string;
};

export const ALERT_RULES = [
  {
    ruleId: "direct_engine_admin_call_unapproved",
    severity: 5,
    title: "Unknown direct NARAEngine admin call",
    description: "A PARAM_ROLE or TREASURY_ROLE NARAEngine function was called directly by an address outside the approved ops router and break glass Safe.",
    fingerprintStrategy: "ruleId:role:functionName:caller",
    evidenceFields: ["txHash", "blockNumber", "wallet", "observedValue", "thresholdValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve manually after confirming caller authorization or incident response completion.",
  },
  {
    ruleId: "param_or_treasury_direct_call_unapproved",
    severity: 5,
    title: "PARAM_ROLE or TREASURY_ROLE action bypassed router",
    description: "A protected engine admin action did not flow through the approved ops router or break glass Safe.",
    fingerprintStrategy: "ruleId:role:functionName:caller",
    evidenceFields: ["txHash", "blockNumber", "wallet", "observedValue", "thresholdValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve manually after the direct call is confirmed as break glass or remediated.",
  },
  {
    ruleId: "role_granted_to_unknown_address",
    severity: 5,
    title: "Role granted to unknown address",
    description: "A protocol role was granted to an address that is not recognized as router, break glass, treasury, admin, ops, or configured protocol contract.",
    fingerprintStrategy: "ruleId:role:account",
    evidenceFields: ["txHash", "blockNumber", "wallet", "observedValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve if the address is later approved and labeled in protocol config.",
  },
  {
    ruleId: "role_admin_changed",
    severity: 5,
    title: "Role admin changed",
    description: "A role admin relationship changed on a monitored v4 contract.",
    fingerprintStrategy: "ruleId:role:newAdminRole",
    evidenceFields: ["txHash", "blockNumber", "observedValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve manually after governance review.",
  },
  {
    ruleId: "large_treasury_withdrawal",
    severity: 5,
    title: "Large treasury withdrawal",
    description: "Treasury ETH fees moved above the configured critical threshold.",
    fingerprintStrategy: "ruleId:recipient:amountBucket",
    evidenceFields: ["txHash", "blockNumber", "wallet", "amount", "observedValue", "thresholdValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve when withdrawal is reconciled with approved treasury operation.",
  },
  {
    ruleId: "unexpected_router_caller",
    severity: 5,
    title: "Unexpected router caller",
    description: "The ops router was called by an address outside the approved operations set.",
    fingerprintStrategy: "ruleId:eventType:caller",
    evidenceFields: ["txHash", "blockNumber", "wallet", "observedValue", "thresholdValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve after caller is approved or access pattern is remediated.",
  },
  {
    ruleId: "reward_reserve_accounting_mismatch",
    severity: 5,
    title: "Reward reserve accounting mismatch",
    description: "Observed reward reserve accounting differs from expected indexed accounting.",
    fingerprintStrategy: "ruleId:sourceRowId",
    evidenceFields: ["txHash", "blockNumber", "amount", "observedValue", "thresholdValue", "viewName", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve when reserve accounting view reconciles.",
  },
  {
    ruleId: "lock_accounting_mismatch",
    severity: 5,
    title: "Lock accounting mismatch",
    description: "Indexed position accounting diverges from expected lock accounting.",
    fingerprintStrategy: "ruleId:positionId",
    evidenceFields: ["txHash", "blockNumber", "positionId", "amount", "observedValue", "thresholdValue", "viewName", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve when lock accounting reconciles.",
  },
  {
    ruleId: "claim_without_matching_reward",
    severity: 5,
    title: "Claim without matching reward",
    description: "A claim event was observed without matching reward accounting evidence.",
    fingerprintStrategy: "ruleId:txHash:positionId:rewardToken",
    evidenceFields: ["txHash", "blockNumber", "wallet", "positionId", "tokenId", "amount", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve when matching reward notification/accounting is indexed.",
  },
  {
    ruleId: "position_owner_unknown_too_long",
    severity: 5,
    title: "Position owner unknown too long",
    description: "A position NFT owner remains the zero-address placeholder beyond the allowed indexing window.",
    fingerprintStrategy: "ruleId:tokenId",
    evidenceFields: ["blockNumber", "tokenId", "positionId", "observedValue", "thresholdValue", "viewName", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve when ERC721 Transfer fills the owner.",
  },
  {
    ruleId: "indexer_lag",
    severity: 5,
    title: "Indexer lag",
    description: "The monitor has fallen behind the configured indexing freshness threshold.",
    fingerprintStrategy: "ruleId:chainId",
    evidenceFields: ["observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when indexed head returns inside freshness threshold.",
  },
  {
    ruleId: "retired_address_detected_in_config",
    severity: 5,
    title: "Retired address detected in config",
    description: "A retired v3 or incident-stack address was detected in monitor configuration.",
    fingerprintStrategy: "ruleId:envName:address",
    evidenceFields: ["observedValue", "thresholdValue", "sourceTable"],
    resolutionCondition: "Resolve by replacing config with fresh active v4 address.",
  },
  {
    ruleId: "large_unlock_24h",
    severity: 4,
    title: "Large unlock within 24h",
    description: "A wallet has a large locked amount estimated to unlock within 24 hours.",
    fingerprintStrategy: "ruleId:wallet",
    evidenceFields: ["wallet", "positionId", "amount", "observedValue", "thresholdValue", "viewName", "sourceRowId"],
    resolutionCondition: "Resolve when the amount is no longer inside the 24h window.",
  },
  {
    ruleId: "large_unlock_7d",
    severity: 4,
    title: "Large unlock within 7d",
    description: "A wallet has a large locked amount estimated to unlock within 7 days.",
    fingerprintStrategy: "ruleId:wallet",
    evidenceFields: ["wallet", "positionId", "amount", "observedValue", "thresholdValue", "viewName", "sourceRowId"],
    resolutionCondition: "Resolve when the amount is no longer inside the 7d window.",
  },
  {
    ruleId: "wallet_concentration_above_threshold",
    severity: 4,
    title: "Wallet concentration above threshold",
    description: "A wallet controls more locked NARA than the configured concentration threshold.",
    fingerprintStrategy: "ruleId:wallet",
    evidenceFields: ["wallet", "amount", "observedValue", "thresholdValue", "viewName", "sourceRowId"],
    resolutionCondition: "Resolve when wallet concentration falls below threshold.",
  },
  {
    ruleId: "large_outgoing_transfer_high_conviction",
    severity: 4,
    title: "Large outgoing transfer by high conviction wallet",
    description: "A high-conviction wallet made a large outgoing NARA transfer.",
    fingerprintStrategy: "ruleId:wallet:txHash",
    evidenceFields: ["txHash", "blockNumber", "wallet", "amount", "observedValue", "thresholdValue", "sourceTable", "sourceRowId"],
    resolutionCondition: "Resolve after transfer is reviewed.",
  },
  {
    ruleId: "large_genesis_holder_unlock",
    severity: 4,
    title: "Large Genesis holder unlock",
    description: "A Genesis holder has a large position entering an unlock window.",
    fingerprintStrategy: "ruleId:wallet:positionId",
    evidenceFields: ["wallet", "positionId", "tokenId", "amount", "observedValue", "thresholdValue", "viewName", "sourceRowId"],
    resolutionCondition: "Resolve when the Genesis position leaves the unlock window or unlocks.",
  },
  {
    ruleId: "abnormal_claim_spike",
    severity: 4,
    title: "Abnormal claim spike",
    description: "Claim volume or count exceeds deterministic spike thresholds.",
    fingerprintStrategy: "ruleId:wallet:window",
    evidenceFields: ["wallet", "amount", "observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when claim activity returns below threshold.",
  },
  {
    ruleId: "router_operation_spike",
    severity: 4,
    title: "Router operation spike",
    description: "Ops router activity exceeds deterministic spike thresholds.",
    fingerprintStrategy: "ruleId:eventType:window",
    evidenceFields: ["observedValue", "thresholdValue", "viewName", "sourceTable"],
    resolutionCondition: "Resolve when router activity returns below threshold.",
  },
  {
    ruleId: "bond_creation_spike",
    severity: 4,
    title: "Bond creation spike",
    description: "Bond creation activity exceeds deterministic spike thresholds.",
    fingerprintStrategy: "ruleId:window",
    evidenceFields: ["observedValue", "thresholdValue", "viewName", "sourceTable"],
    resolutionCondition: "Resolve when bond creation returns below threshold.",
  },
  {
    ruleId: "fresh_wallet_cluster_activity",
    severity: 4,
    title: "Fresh wallet cluster activity",
    description: "Many fresh wallets are active inside the configured activity window.",
    fingerprintStrategy: "ruleId:window",
    evidenceFields: ["observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when fresh activity falls below threshold.",
  },
  {
    ruleId: "repeated_admin_attempts",
    severity: 4,
    title: "Repeated admin attempts",
    description: "An address made repeated admin attempts inside the deterministic window.",
    fingerprintStrategy: "ruleId:wallet",
    evidenceFields: ["wallet", "observedValue", "thresholdValue", "viewName", "sourceTable"],
    resolutionCondition: "Resolve when repeated attempts stop or are reviewed.",
  },
  {
    ruleId: "medium_unlock_cliff",
    severity: 3,
    title: "Medium unlock cliff",
    description: "A medium-sized unlock cliff is approaching.",
    fingerprintStrategy: "ruleId:wallet:positionId",
    evidenceFields: ["wallet", "positionId", "amount", "observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when position leaves the unlock window.",
  },
  {
    ruleId: "wallet_risk_score_above_threshold",
    severity: 3,
    title: "Wallet risk score above threshold",
    description: "A wallet deterministic risk score crossed the configured threshold.",
    fingerprintStrategy: "ruleId:wallet",
    evidenceFields: ["wallet", "observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when wallet risk score falls below threshold.",
  },
  {
    ruleId: "short_duration_lock_concentration",
    severity: 3,
    title: "Short duration lock concentration",
    description: "Short-duration locks are concentrated above the configured threshold.",
    fingerprintStrategy: "ruleId:wallet",
    evidenceFields: ["wallet", "observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when short-duration concentration falls below threshold.",
  },
  {
    ruleId: "nft_metadata_missing",
    severity: 3,
    title: "NFT metadata missing",
    description: "An NFT row exists without expected position metadata.",
    fingerprintStrategy: "ruleId:tokenId",
    evidenceFields: ["tokenId", "observedValue", "thresholdValue", "viewName", "sourceRowId"],
    resolutionCondition: "Resolve when PositionMinted or GenesisPositionMinted metadata arrives.",
  },
  {
    ruleId: "position_without_nft_metadata",
    severity: 3,
    title: "Position without NFT metadata",
    description: "A lock position exists without matching NFT metadata when one is expected.",
    fingerprintStrategy: "ruleId:positionId",
    evidenceFields: ["positionId", "wallet", "amount", "viewName", "sourceRowId"],
    resolutionCondition: "Resolve when matching NFT metadata is indexed or position is confirmed raw.",
  },
  {
    ruleId: "claim_rate_drop",
    severity: 3,
    title: "Claim rate drop",
    description: "Claim activity dropped below deterministic baseline.",
    fingerprintStrategy: "ruleId:window",
    evidenceFields: ["observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when claim activity returns above baseline.",
  },
  {
    ruleId: "low_protocol_activity",
    severity: 3,
    title: "Low protocol activity",
    description: "Protocol activity dropped below deterministic baseline.",
    fingerprintStrategy: "ruleId:window",
    evidenceFields: ["observedValue", "thresholdValue", "viewName"],
    resolutionCondition: "Resolve when activity returns above baseline.",
  },
] as const satisfies readonly AlertRuleDefinition[];

export type AlertRuleId = (typeof ALERT_RULES)[number]["ruleId"];

const rulesById = new Map<string, AlertRuleDefinition>(
  ALERT_RULES.map((rule) => [rule.ruleId, rule]),
);

export function getAlertRule(ruleId: AlertRuleId): AlertRuleDefinition {
  const rule = rulesById.get(ruleId);
  if (!rule) {
    throw new Error(`Unknown alert rule: ${ruleId}`);
  }
  return rule;
}
